# The block you want to use as the shop.
shopBlock: 'minecraft:barrel'

# Allows the use of shop blocks. Setting to false will disable players using specified shop block to open shop GUI
# WARNING: Setting to false will allow breaking of existing shop blocks without deleting shop!
enableShopBlock: true

# This enables admin shops that don't need stock. Created by typing /shop adminshop, requires tradingshop.admin permission
enableAdminShop: true

# The block you want to open the stock GUI.
stockBlock: 'minecraft:composter'

# Allows the use of stock blocks. Setting to false will disable players using specified stock block to open stock GUI
# WARNING: Setting to false will allow players to destroy stock blocks!
enableStockBlock: true

# Allows to open the stock GUI using /shop stock.
enableStockCommand: true

# Number of pages to have in the stock GUI.
stockPages: 5

# Time in seconds before receiving another message about being out of stock of that item when someone tries to buy
noStockCooldown: 300

# Amount of money needed to create a shop.
# Set to 0 to disable.
createCost: 0.0

# Amount of money returned when deleting a shop.
# Set to 0 to disable.
returnAmount: 0.0

# Amount of days of player inactivity before deleting theirs shops. 
# Set to 0 to disable.
maxInactiveDays: 0

# Delete block on shop remove
deleteBlock: false

# Show particles in shop blocks
showParticles: true

# Require to set the trade-shop flag in the regions for it to work.
# Only works if WorldGuard is installed.
enableWorldGuardFlag: true

# Set whether you want to use permission nodes or not.
# (set to false if you don't have a permission plugin).
usePermissions: true

# Only works if usePermissions is set to false.
# If it's set to true, then you'll need to edit the limit via permission nodes.
# Set to -1 to disable the limit
defaultShopLimit: 5

# Allow managing the shop remotely using "/shop manage <id>" command.
remoteManage: true

# Allow anyone to use "/shop view <id>" command to view other players shop remotely
remoteShopping: false

# Allow public use of "/shop list <player>" command
publicListCommand: false

#TRANSLATIONS
noPermissions: "&cYou do not have permission for this command!"
shopNotOwned: "&cYou do not own this shop!"
shopDeleted: "&7Targeted shop has been &cDELETED&7!"
shopCreated: "&7Targeted shop has been &aCREATED&7!"
shopLimit: "&cYou do not have permission or reached your shops amount limit!"
noItems: "&cYou do not have enough item(s) to buy from this shop!"
noStock: "&cThis shop is currently out of stock of that item(s)!"
noStockNotify: "&cOne of your shops is currently out of stock! &o(%s)"
buy: "&7You bought&a %in &7for&c %out&7!"
sell: "&7%p has bought&7&c %in &7for&a %out&7!"
noMoney: "&cYou do not have enough money to create a shop. You need at least &o$"
reload: "&7Configuration file reloaded."
adminShop: "Admin Shop"
normalShop: "&l%player%'s Shop"
sellTitle: "ITEMS FOR SALE"
buyTitle: "PRICE TO BUY ITEMS"
deleteTitle: "DELETE"
createTitle: "CREATE"
broadcastOn: "Broadcast ON"
broadcastOff: "Broadcast OFF"
createShopTitle: "Create shop trades!"
stockTitle: "Shop Stock Inventory"
page: "Page"
buyAction: "BUY"
shopBusy: "&6Shop is currently busy, try again soon!"
stockCommandDisabled: "&cThe /shop stock command has been disabled!"
playerInventoryFull: "&cYour inventory is FULL! Cannot buy any items!"
noPlayerShop: "&cPlayer name does not exist! Cannot list player shop!"
noPlayerFound: "&cPlayer cannot be found!"
noRemoteManage: "&cRemote management of shops has been disabled!"
noRemoteShops: "&cRemote shopping has been disabled!"
noShopFound: "&cNo shop can be found!"
playerShopCreated: "&7Shop has been &aCREATED&7 for&a %p &7!"
shopIDDeleted: "&cShop id&a %id &chas been DELETED!"
shopIntegerError: "&cShop id must be an integer greater than 0!"
targetMismatch: "&cTargeted block must match set shop block!"
disabledShopBlock: "&cCannot create shop location when shop blocks are disabled!"
adminShopDisabled: "&cAdmin shops have been disabled, cannot create!"
existingShop: "&cCannot create shop where existing shop is already located!"

# Do not edit this
configVersion: 2.2