name: TradingShops
main: es.elzoo.tradingshops.TradingShops
author: Chistian95
website: https://elzoo.es
version: "2.1.3"
api-version: "1.16"
softdepend: [Vault, WorldGuard]
commands:
  tradeshop:
    description: "Main shop command"
    usage: /shop
    aliases: [shop]
