# The block you want to use as the shop.
shopBlock: 'minecraft:barrel'

# The block you want to open the stock GUI.
stockBlock: 'minecraft:composter'

# Allows to open the stock GUI using /shop stock.
enableStockCommand: true

# Number of pages to have in the stock GUI.
stockPages: 5

# Amount of money needed to create a shop. 
# Set to 0 to disable.
createCost: 0.0

# Amount of money returned when deleting a shop. 
# Set to 0 to disable.
returnAmount: 0.0

# Amount of days of player inactivity before deleting theirs shops. 
# Set to 0 to disable.
maxInactiveDays: 0

# Delete block on shop remove
deleteBlock: false

# Show particles in shop blocks
showParticles: true

# Require to set the trade-shop flag in the regions for it to work.
# Only works if WorldGuard is installed.
enableWorldGuardFlag: true

# Set wether you want to use permission nodes or not.
# (set to false if you don't have a permission plugin).
usePermissions: true

# Only works if usePermissions is set to false.
# If it's set to true, then you'll need to edit the limit via permission nodes.
# Set to -1 to disable the limite
defaultShopLimit: 5


#TRANSLATIONS
noPermissions: "&cYou do not have permissions to do that."
deleteShop: "&7Click on the shop you want to delete."
createShop: "&7Click the block you want to create the shop on."
shopNotOwned: "&cYou do not own this shop!" 
shopDeleted: "&7Shop deleted."
shopCreated: "&7Shop created."
shopLimit: "&cYou have reached your shops amount limit."
noItems: "&cYou do not have enough items."
noStock: "&cThe shop does not have enough stock."
noStockNotify: "&cOne of your shops has run out of stock! &o(%s)"
buy: "&7You bought&7 %in &7for&c %out&7."
sell: "&7%p has bought&7 %in &7for&c %out&7."
noMoney: "&cYou do not have enough money to create a shop. You need at least &o$"
reload: "&7Configuration file reloaded."
adminShop: "Admin Shop"
normalShop: "%player%'s shop"
sellTitle: "You sell"
buyTitle: "For"
deleteTitle: "DELETE"
createTitle: "CREATE"
broadcastOn: "Broadcast ON"
broadcastOff: "Broadcast OFF"
createShopTitle: "Create Shop"
stockTitle: "Stock"
page: "Page"
buyAction: "BUY"

# Do not edit this
configVersion: 1.5